using System;
using System.Collections.Generic;

[Serializable]
public class ExerciseSettingsData
{
    public bool usePacemaker = true;
    public bool allowWithoutPacemaker = true;

    // Pacemaker speed in percent of full track length per minute. 300 = full route in 20 seconds.
    public float defaultSpeed = 300f;
    public int durationMs = 60000;
    public float lineThickness = 6f;

    public bool showTrack = true;

    public bool useSensor = false;
    public float sensorSensitivity = 1f;

    public float corridorWidthCm = 4.0f;
    public float hitRadiusCm = 5.0f;

    public float workspaceWidthMm = 1000f;
    public float workspaceHeightMm = 600f;

    public float lagThresholdCm = 2.0f;
    public int exitDebounceMs = 100;

    public float stopSpeedThresholdMmS = 10f;
    public int stopConfirmMs = 150;

    public bool trackDeviation = true;
    public bool saveSessionResult = true;

    public bool audioEnabled = true;
    public float audioVolume01 = 0.7f;

    public bool metronomeEnabled = false;
    public float metronomeBpm = 60f;
    public float metronomeVolume01 = 1f;

    public PointerInputSource inputSource = PointerInputSource.Mouse;

    // Default loop mode for new pacemakers generated by ExerciseSaver.
    public PacemakerLoopMode defaultPacemakerLoopMode = PacemakerLoopMode.Loop;

    // Body point bindings: up to 3 active body points, each linked with tracker and cursor.
    public List<BodyPointBindingData> bodyPointBindings = new();
    public BodyPointId activeBodyPointId = BodyPointId.RightForearm;
    public string activeBodyPointZoneId = "zone_right_forearm";

    public List<PacemakerSettingsData> pacemakers = new();
}
